### PR TITLE
Upgrade to .NET Standard 2.0

### LINKED ISSUE #114: Upgrade to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by IceAndSnow**
Closes #114

### CODE REVIEW

**Comment by IceAndSnow** [comment]
@nover @pingvinen 

In src/core/unittests/Configuration/ConfigBaseTests.cs
The preprocessor directive has been changed from
```
#if NETSTANDARD1_6
[...]
#endif
```
to
```
#if NETSTANDARD2_0
[...]
#endif
```

However these tests are not run. This is both the case for my machine as well as the CI pipeline. They were not tested by the CI pipeline before these modifications either.

Perhaps this preprocessor directive should not exist (in the unittests project that is)?

**Comment by pingvinen** [comment]
Ditching 1.6 for 2.0 is good.. might as well keep up with the times.

This PR however also removes the .NET 4.5 support. I know we have discussed this offline, but I do not remember if we came to a conclusion. Anyway... that part should maybe go in its own PR to make it painfully obvious for someone looking at history etc.

What do you think @nover ?

**Comment by pingvinen** [comment]
Support for .NET 4.5 was removed in https://github.com/rapidcore/rapidcore/pull/119.

I have rebased the branch for this PR.

**Review by nover — DISMISSED** [review]

**Comment by nover** [comment]
@pingvinen @IceAndSnow is this PR ready for merge?

**Comment by pingvinen** [comment]
Just tried upgrading the dotnet sdk version used in Travis to `2.2.203` but that failed to install the package, so I removed that change.

If the build succeeds I think we are good to merge @nover

**Comment by pingvinen** [comment]
Closes #120

**Review by nover — APPROVED** [review]

**Pull request merged**
